services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--quiet"]

  backend:
    build: ./backend
    container_name: air_quality_backend
    depends_on:
      - mongo
    ports:
      - "${FLASK_PORT}:5000"
    networks:
      - app_network
    env_file:
      - .env
    volumes:
      - ./backend:/app

  dashboard:
    image: node:22.11-alpine
    container_name: air_quality_dashboard
    depends_on:
      - backend
    ports:
      - "${DASHBOARD_PORT}:3000"
    volumes:
      - ./dashboard:/usr/src/dashboard
    working_dir: /usr/src/dashboard
    networks:
      - app_network
    command: >
      sh -c "npm install && npx ng serve --host 0.0.0.0 --port 3000 --poll 2000"

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
